version: '2'
services:
    cotaeasyemailservice-app:
        image: cotaeasyemailservice
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://cotaeasyemailservice-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=CotaEasyEmailService
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    cotaeasyemailservice-mongodb:
        extends:
            file: mongodb.yml
            service: cotaeasyemailservice-mongodb
